# Generated by Django 5.1.6 on 2025-04-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoPesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('frequency', models.IntegerField()),
            ],
        ),
    ]
