# Generated by Django 5.1.6 on 2025-04-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamview', '0002_historicopesquisa'),
    ]

    operations = [
        migrations.CreateModel(
            name='maisJogados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('players', models.CharField(max_length=15)),
                ('image', models.URLField()),
            ],
        ),
    ]
