# Generated by Django 5.1.6 on 2025-04-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamview', '0003_maisjogados'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaisJogadosHist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('rating', models.CharField(max_length=15)),
                ('released', models.CharField(max_length=15)),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='MenosJogadosHist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('rating', models.CharField(max_length=15)),
                ('released', models.CharField(max_length=15)),
                ('image', models.URLField()),
            ],
        ),
    ]
