# Generated by Django 5.1.6 on 2025-04-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamview', '0004_maisjogadoshist_menosjogadoshist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menosjogadoshist',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
