# Generated by Django 5.1.6 on 2025-04-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamview', '0005_alter_menosjogadoshist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogos',
            name='released_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
